// <auto-generated />
using LibroAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibroAPI.Migrations
{
    [DbContext(typeof(LibroContext))]
    [Migration("20240830005632_Migracion Inicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibroAPI.Models.Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnioPublicacion")
                        .HasColumnType("int");

                    b.Property<string>("Autor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LibroSet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnioPublicacion = 2008,
                            Autor = "Robert C. Martin",
                            Titulo = "Clean Code"
                        },
                        new
                        {
                            Id = 2,
                            AnioPublicacion = 1999,
                            Autor = "Andrew Hunt, David Thomas",
                            Titulo = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 3,
                            AnioPublicacion = 1994,
                            Autor = "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
                            Titulo = "Design Patterns: Elements of Reusable Object-Oriented Software"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
